ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS lat FLOAT;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS lng FLOAT;
ALTER TABLE public.users    ADD COLUMN IF NOT EXISTS lat FLOAT;
ALTER TABLE public.users    ADD COLUMN IF NOT EXISTS lng FLOAT;
