import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how DogCareGH (888 Capital City Ventures) collects, uses, and protects your personal data in accordance with Ghana's Data Protection Act 2012.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "#f8fafb" }}>
      {/* Nav */}
      <nav className="border-b border-white/10 px-6 py-4 md:px-12" style={{ backgroundColor: "#0a2e30" }}>
        <div className="mx-auto flex max-w-4xl items-center justify-between">
          <Link href="/"><img src="/weblogo.png" alt="DogCareGH" className="h-10 w-auto" /></Link>
          <Link href="/" className="text-xs font-semibold text-white/70 transition hover:text-white">← Back to home</Link>
        </div>
      </nav>

      {/* Content */}
      <div className="mx-auto max-w-4xl px-6 py-12 md:px-8 md:py-16">
        <div className="mb-10">
          <p className="mb-2 text-xs font-semibold uppercase tracking-widest" style={{ color: "#00b096" }}>Legal</p>
          <h1 className="text-3xl font-extrabold md:text-4xl" style={{ color: "#0a2e30" }}>Privacy Policy</h1>
          <p className="mt-3 text-sm text-gray-500">Last updated: June 2025</p>
        </div>

        <div className="space-y-10 rounded-2xl border border-gray-100 bg-white px-6 py-8 shadow-sm md:px-10">

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>1. Who We Are</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              DogCareGH is a platform operated by <strong>888 Capital City Ventures</strong> (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), a business registered in Ghana. We connect dog owners with trusted pet care providers across Ghana. This Privacy Policy explains how we collect, use, store, and protect your personal information in accordance with Ghana&rsquo;s <strong>Data Protection Act, 2012 (Act 843)</strong>.
            </p>
            <p className="mt-3 text-sm leading-relaxed text-gray-600">
              By using DogCareGH, you consent to the practices described in this policy. If you have questions, contact us at <a href="mailto:support@dogcaregh.com" className="font-semibold hover:underline" style={{ color: "#00b096" }}>support@dogcaregh.com</a>.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>2. Information We Collect</h2>
            <p className="mb-3 text-sm leading-relaxed text-gray-600">We collect information you provide directly and information generated by your use of the platform:</p>
            <ul className="space-y-2 text-sm text-gray-600">
              {[
                { title: "Account information", desc: "Name, email address, and password when you register." },
                { title: "Profile information", desc: "Location/neighbourhood, profile photo, biography, and for providers: years of experience, services offered, and availability." },
                { title: "Dog information", desc: "Your dog's name, breed, age, size, and vaccination status." },
                { title: "Booking information", desc: "Service dates, booking history, messages exchanged with providers or owners." },
                { title: "Payment information", desc: "Payments are processed by Paystack. We do not store your card or mobile money details — only booking amounts and transaction references." },
                { title: "Payout information", desc: "For providers: your mobile money network and number for withdrawals." },
                { title: "Communications", desc: "Messages you send through our in-app messaging system." },
                { title: "Usage data", desc: "Pages visited, search queries, and device/browser information." },
              ].map(item => (
                <li key={item.title} className="flex gap-2">
                  <span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span>
                  <span><strong>{item.title}:</strong> {item.desc}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>3. How We Use Your Information</h2>
            <ul className="space-y-2 text-sm text-gray-600">
              {[
                "To create and manage your account",
                "To facilitate bookings between owners and providers",
                "To process payments and provider payouts via Paystack",
                "To send transactional emails (booking confirmations, payment receipts, notifications) via Resend",
                "To display your public provider profile on our search and marketplace",
                "To resolve disputes and support requests",
                "To improve the platform and understand how it is used",
                "To comply with legal obligations under Ghanaian law",
              ].map(item => (
                <li key={item} className="flex gap-2">
                  <span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>4. Information We Share</h2>
            <p className="mb-3 text-sm leading-relaxed text-gray-600">We do not sell your personal data. We share it only in the following circumstances:</p>
            <ul className="space-y-2 text-sm text-gray-600">
              <li className="flex gap-2"><span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span><span><strong>With other users:</strong> Your public profile (name, neighbourhood, photo, services, reviews) is visible to users of the platform. Booking-specific information is shared between the owner and provider involved in that booking.</span></li>
              <li className="flex gap-2"><span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span><span><strong>With service providers:</strong> We use Supabase (database and authentication), Paystack (payments), and Resend (email). These providers process data on our behalf and are bound by their own privacy policies.</span></li>
              <li className="flex gap-2"><span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span><span><strong>For legal reasons:</strong> If required by law, court order, or to protect the rights and safety of our users or the public.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>5. Data Retention</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              We retain your personal data for as long as your account is active or as needed to provide our services. If you close your account, we will delete or anonymise your personal data within 90 days, except where we are required to retain it for legal or regulatory purposes (such as transaction records).
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>6. Data Security</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              We take reasonable technical and organisational measures to protect your data, including encrypted connections (HTTPS), secure authentication via Supabase, and restricted access to production systems. No method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>7. Your Rights</h2>
            <p className="mb-3 text-sm leading-relaxed text-gray-600">Under Ghana&rsquo;s Data Protection Act 2012, you have the right to:</p>
            <ul className="space-y-2 text-sm text-gray-600">
              {[
                "Access the personal data we hold about you",
                "Request correction of inaccurate data",
                "Request deletion of your data (subject to legal retention requirements)",
                "Object to how we process your data",
                "Withdraw consent at any time",
              ].map(item => (
                <li key={item} className="flex gap-2">
                  <span style={{ color: "#00b096" }} className="mt-0.5 shrink-0">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-3 text-sm text-gray-600">
              To exercise any of these rights, email us at <a href="mailto:support@dogcaregh.com" className="font-semibold hover:underline" style={{ color: "#00b096" }}>support@dogcaregh.com</a>. We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>8. Cookies</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              We use essential cookies to keep you logged in and maintain your session. We do not use advertising or tracking cookies. You can disable cookies in your browser settings, but this may affect your ability to use the platform.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>9. Children</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              DogCareGH is not intended for users under the age of 18. We do not knowingly collect personal data from children. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>10. Changes to This Policy</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              We may update this policy from time to time. We will notify you of significant changes by email or by displaying a notice on the platform. Continued use of DogCareGH after changes take effect constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-extrabold" style={{ color: "#0a2e30" }}>11. Contact</h2>
            <p className="text-sm leading-relaxed text-gray-600">
              For any privacy-related questions or to exercise your data rights, contact <strong>888 Capital City Ventures</strong> at:<br />
              <a href="mailto:support@dogcaregh.com" className="font-semibold hover:underline" style={{ color: "#00b096" }}>support@dogcaregh.com</a>
            </p>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-100 px-6 py-8 text-center text-sm text-gray-400 md:px-12">
        © {new Date().getFullYear()} DogCareGH · 888 Capital City Ventures.
        <span className="mx-2">·</span>
        <Link href="/terms" className="hover:underline">Terms</Link>
        <span className="mx-2">·</span>
        <Link href="/privacy" className="hover:underline">Privacy</Link>
        <span className="mx-2">·</span>
        <Link href="/contact" className="hover:underline">Contact</Link>
      </footer>
    </div>
  );
}
